# Generated by Django 4.1.7 on 2023-03-31 13:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0003_counselordata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counselordata',
            name='usercontacts',
        ),
        migrations.AddField(
            model_name='counselordata',
            name='usercontacts',
            field=models.ManyToManyField(blank=True, related_name='contacts', to=settings.AUTH_USER_MODEL),
        ),
    ]
