# Generated by Django 4.1.7 on 2023-03-31 13:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0004_remove_counselordata_usercontacts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counselordata',
            name='usercontacts',
            field=models.ManyToManyField(blank=True, related_name='mycontacts', to=settings.AUTH_USER_MODEL),
        ),
    ]
