# Generated by Django 4.1.7 on 2023-03-31 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_counselordata_usercontacts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counselordata',
            name='usercontacts',
        ),
        migrations.AddField(
            model_name='counselordata',
            name='usercontacts',
            field=models.TextField(blank=True),
        ),
    ]
