# Generated by Django 4.1.7 on 2023-03-31 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_remove_counselordata_usercontacts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='bygpt',
            field=models.BooleanField(default=False),
        ),
    ]
